const express = require('express')
const bodyParser = require('body-parser')
const logger = require('morgan')
const app = express()
const cors = require('cors')
const ShapeController = require('./controllers/ShapeController')

app.use(bodyParser.urlencoded({ extended: false }))
app.use(bodyParser.json())
app.use(logger('dev'))
app.use(cors())
app.use('/', ShapeController)
app.listen(2046, () => console.log(`LISTENING ON PORT 2046`))